//! Turning the encryption feature off is a real option (S14, [D-095](../../../../docs/DECISIONS.md),
//! [encryption contract §10](../../../../docs/ENCRYPTION-CONTRACT.md)).
//!
//! A format feature you cannot roll back is not a feature, it is a one-way door. Contract §10 makes
//! the promise precise: **an unencrypted store is byte-identical to before** — no feature bit, no
//! extension, no new bytes, no behaviour change — and the flag is **explicit**, so a store is
//! encrypted because it was configured to be and never because a part happened to carry a bit.
//!
//! §10 says the compatibility fixtures prove the byte-identity half, so that is made to do actual
//! work here: the committed v1/v2/v3 trees are opened, verified, and compared to themselves
//! afterwards. A store that rewrites itself on open is not one you can roll back to.
//!
//! **What is deliberately not claimed.** These gates do not rebuild a fixture and diff it against
//! today's writer. `scripts/make-fixtures.sh` regenerates `v3` whenever the format is bumped — only
//! `v1` and `v2` are never-regenerated bytes, and they predate the current writer entirely — so a
//! rebuild-and-diff would be asserting something the fixture corpus was never designed to hold.
//! What it *can* hold is that nothing S14 added shows up in any of them, and that is what is
//! checked.
//!
//! That gate was written, failed for exactly this reason, and was **deleted rather than parked
//! behind `#[ignore]`** — a disabled test is a claim nobody is checking. It is logged as
//! [issue #39](https://github.com/Bobcatsfan33/PrismDB/issues/39): when format v3 stabilizes, its
//! bytes get frozen like v1/v2 and the byte-for-byte gate comes back against the frozen copy. A
//! regenerable fixture is one refresh away from the S2 failure the README records — a drift check
//! that regenerates what it is checking, and so passes by construction while testing nothing.

use prism_engine::keys::{KeyProvider, SoftwareKeystore};
use prism_engine::Engine;
use prism_part::store::{StoreConfig, STORE_VERSION};
use prism_types::Query;
use std::collections::BTreeMap;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

static N: AtomicU64 = AtomicU64::new(0);

fn tmp(tag: &str) -> PathBuf {
    let n = N.fetch_add(1, Ordering::SeqCst);
    let p = std::env::temp_dir().join(format!("prism-rollback-{tag}-{}-{n}", std::process::id()));
    let _ = std::fs::remove_dir_all(&p);
    p
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

fn config() -> StoreConfig {
    StoreConfig {
        format_version: STORE_VERSION,
        dim: 64,
        nlist: 16,
        pq_m: 8,
        seed: 9,
        kmeans_restarts: 1,
        block_size: prism_part::format::DEFAULT_BLOCK_SIZE,
        partitions: Default::default(),
        promote: Vec::new(),
    }
}

fn events() -> Vec<prism_types::Event> {
    prism_engine::corpus::generate(prism_engine::corpus::Kind::Zipf, 400, 4)
}

fn hits(engine: &Engine, tenant: &str) -> Vec<String> {
    engine
        .search(&Query {
            text: "the tool call timed out retrying".into(),
            k: 15,
            tenant: Some(tenant.into()),
            rerank: 40,
            ..Default::default()
        })
        .unwrap()
        .hits
        .into_iter()
        .map(|h| h.event.event_id)
        .collect()
}

/// Every file of every live part, keyed by `part/file`.
fn part_files(engine: &Engine) -> BTreeMap<String, Vec<u8>> {
    let mut out = BTreeMap::new();
    for part_id in engine.snapshot().unwrap().part_ids() {
        let dir = engine.store.part_dir(&part_id);
        for entry in std::fs::read_dir(&dir).unwrap() {
            let entry = entry.unwrap();
            if !entry.file_type().unwrap().is_file() {
                continue;
            }
            let name = entry.file_name().to_string_lossy().into_owned();
            out.insert(
                format!("{part_id}/{name}"),
                std::fs::read(entry.path()).unwrap(),
            );
        }
    }
    out
}

#[test]
fn a_never_encrypted_store_sets_no_feature_bit_and_carries_no_envelope() {
    let root = tmp("no-bit");
    let engine = Engine::init(&root, config()).unwrap();
    engine.ingest(events(), 1_760_000_000_000).unwrap();

    let ids = engine.snapshot().unwrap().part_ids();
    assert!(!ids.is_empty());
    for id in &ids {
        let reader = engine.open_part(id).unwrap();
        assert_eq!(
            reader.manifest.feature_flags & prism_part::format::FEATURE_ENCRYPTION,
            0,
            "part {id} of an unencrypted store must not set the encryption feature bit"
        );
        assert!(
            !reader.is_encrypted(),
            "part {id} must not report itself as encrypted"
        );
        assert!(
            reader.encryption_envelope().is_none(),
            "part {id} must carry no encryption envelope"
        );
        assert!(
            !reader
                .manifest
                .extensions
                .iter()
                .any(|e| e.id == prism_part::ext::EXT_S14_ENCRYPTION),
            "part {id} must carry no S14 extension at all"
        );
    }
    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn attaching_a_key_service_to_an_existing_store_leaves_its_old_parts_untouched() {
    // Turning the flag ON must not reach backwards. Parts written before it was on stay plaintext,
    // stay byte-identical, and stay readable -- there is no migration, and nothing is rewritten.
    let root = tmp("attach");
    let before = {
        let engine = Engine::init(&root, config()).unwrap();
        engine.ingest(events(), 1_760_000_000_000).unwrap();
        part_files(&engine)
    };
    assert!(!before.is_empty());

    let keystore: Arc<dyn KeyProvider> = Arc::new(SoftwareKeystore::new("key-v1", [11u8; 32]));
    let engine = Engine::open(&root).unwrap().with_keys(keystore);
    assert_eq!(
        part_files(&engine),
        before,
        "attaching a key service must not rewrite a single byte of an existing part"
    );
    assert!(
        !hits(&engine, "t1").is_empty(),
        "and the old plaintext parts must still answer"
    );
    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn detaching_the_key_service_from_a_never_encrypted_store_changes_nothing() {
    // The rollback itself. A store that never wrote an encrypted part must be completely unaffected
    // by the feature being turned on and back off -- same bytes, same answers, no key service
    // needed to open it.
    let root = tmp("detach");
    let keystore: Arc<dyn KeyProvider> = Arc::new(SoftwareKeystore::new("key-v1", [11u8; 32]));

    // Flag on, but nothing ingested under it: the store has no encrypted part.
    let with_keys = Engine::init(&root, config())
        .unwrap()
        .with_keys(Arc::clone(&keystore));
    drop(with_keys);

    // Flag off. Ingest, and the result is an ordinary unencrypted store.
    let rolled_back = Engine::open(&root).unwrap();
    rolled_back.ingest(events(), 1_760_000_000_000).unwrap();
    let expected = hits(&rolled_back, "t1");
    assert!(!expected.is_empty());
    let bytes = part_files(&rolled_back);

    for id in rolled_back.snapshot().unwrap().part_ids() {
        assert!(!rolled_back.open_part(&id).unwrap().is_encrypted());
    }

    // Re-opened with no key service at all, it is the same store. Nothing about the rollback
    // requires the key service to still exist -- which is the whole point.
    let reopened = Engine::open(&root).unwrap();
    assert_eq!(part_files(&reopened), bytes);
    assert_eq!(hits(&reopened, "t1"), expected);
    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn a_store_holding_both_eras_answers_across_them() {
    // The state a real rollback leaves: parts from before the flag was on, and parts from while it
    // was. A store must serve both, because "roll it back" cannot mean "and lose the data you wrote
    // while it was on".
    let root = tmp("mixed");
    let plain_engine = Engine::init(&root, config()).unwrap();
    plain_engine.ingest(events(), 1_760_000_000_000).unwrap();
    let plain_parts: Vec<String> = plain_engine.snapshot().unwrap().part_ids();
    drop(plain_engine);

    let keystore: Arc<dyn KeyProvider> = Arc::new(SoftwareKeystore::new("key-v1", [11u8; 32]));
    let mixed = Engine::open(&root).unwrap().with_keys(keystore);
    mixed
        .ingest(
            prism_engine::corpus::generate(prism_engine::corpus::Kind::Zipf, 400, 9),
            1_760_000_100_000,
        )
        .unwrap();

    let all: Vec<String> = mixed.snapshot().unwrap().part_ids();
    let new_parts: Vec<&String> = all.iter().filter(|p| !plain_parts.contains(p)).collect();
    assert!(!new_parts.is_empty(), "the second ingest must add parts");

    for id in &plain_parts {
        assert!(
            !mixed.open_part(id).unwrap().is_encrypted(),
            "a part written before the flag was on must stay plaintext: {id}"
        );
    }
    for id in &new_parts {
        assert!(
            mixed.open_part(id).unwrap().is_encrypted(),
            "a part written while the flag was on must be sealed: {id}"
        );
    }
    assert!(
        !hits(&mixed, "t1").is_empty(),
        "a store holding both eras must still answer"
    );
    let _ = std::fs::remove_dir_all(root);
}

/// Copy a committed fixture out of the repo, so nothing here can write to it.
fn fixture_copy(name: &str, into: &std::path::Path) {
    fn copy_tree(from: &std::path::Path, to: &std::path::Path) {
        std::fs::create_dir_all(to).unwrap();
        for entry in std::fs::read_dir(from).unwrap() {
            let entry = entry.unwrap();
            let dst = to.join(entry.file_name());
            if entry.file_type().unwrap().is_dir() {
                copy_tree(&entry.path(), &dst);
            } else {
                std::fs::copy(entry.path(), &dst).unwrap();
            }
        }
    }
    copy_tree(&repo_root().join("testing/compat").join(name), into);
}

/// Every file under `dir`, by relative path — for proving a read wrote nothing.
fn tree_bytes(dir: &std::path::Path) -> BTreeMap<String, Vec<u8>> {
    fn walk(base: &std::path::Path, dir: &std::path::Path, out: &mut BTreeMap<String, Vec<u8>>) {
        for entry in std::fs::read_dir(dir).unwrap() {
            let entry = entry.unwrap();
            if entry.file_type().unwrap().is_dir() {
                walk(base, &entry.path(), out);
            } else {
                let rel = entry
                    .path()
                    .strip_prefix(base)
                    .unwrap()
                    .to_string_lossy()
                    .into_owned();
                out.insert(rel, std::fs::read(entry.path()).unwrap());
            }
        }
    }
    let mut out = BTreeMap::new();
    walk(dir, dir, &mut out);
    out
}

#[test]
fn the_frozen_compatibility_fixtures_gained_no_encryption_bytes() {
    // §10's claim that "the compatibility fixtures prove it", made to do actual work. v1 and v2 are
    // bytes their versions shipped and are never regenerated; v3 is the current format's fixture.
    // None of them may have grown a feature bit, an extension, or a byte — and reading one must
    // write nothing back, because a store that rewrites itself on open is not one you can roll back
    // to.
    for name in ["v1", "v2", "v3"] {
        let root = tmp(&format!("frozen-{name}"));
        fixture_copy(name, &root);
        let before = tree_bytes(&root);
        assert!(!before.is_empty(), "the {name} fixture must exist");

        let engine = Engine::open(&root).unwrap_or_else(|e| panic!("{name} must open: {e}"));
        for id in engine.snapshot().unwrap().part_ids() {
            let reader = engine.open_part(&id).unwrap();
            assert_eq!(
                reader.manifest.feature_flags & prism_part::format::FEATURE_ENCRYPTION,
                0,
                "{name} part {id} grew the encryption feature bit"
            );
            assert!(
                !reader
                    .manifest
                    .extensions
                    .iter()
                    .any(|e| e.id == prism_part::ext::EXT_S14_ENCRYPTION),
                "{name} part {id} grew an S14 extension"
            );
            reader.verify().unwrap_or_else(|e| {
                panic!("{name} part {id} must still verify with no key service: {e}")
            });
        }
        assert_eq!(
            tree_bytes(&root),
            before,
            "reading the {name} fixture rewrote it"
        );
        let _ = std::fs::remove_dir_all(root);
    }
}

#[test]
fn a_frozen_fixture_reads_the_same_with_a_key_service_attached() {
    // Turning the flag on must not make a pre-existing store refuse, migrate, or rewrite itself.
    // The flag is explicit: these parts carry no bit, so they are plaintext, key service or not.
    let root = tmp("frozen-with-keys");
    fixture_copy("v3", &root);
    let before = tree_bytes(&root);

    let keystore: Arc<dyn KeyProvider> = Arc::new(SoftwareKeystore::new("key-v1", [11u8; 32]));
    let engine = Engine::open(&root).unwrap().with_keys(keystore);
    for id in engine.snapshot().unwrap().part_ids() {
        let reader = engine.open_part(&id).unwrap();
        assert!(!reader.is_encrypted());
        assert!(
            reader.cipher().is_none(),
            "a plaintext part must not be handed a cipher just because one exists"
        );
        reader.verify().unwrap();
    }
    assert_eq!(
        tree_bytes(&root),
        before,
        "attaching a key service rewrote a frozen fixture"
    );
    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn two_never_encrypted_stores_built_from_one_input_are_byte_identical() {
    // Encryption introduced no nondeterminism into the plaintext path. If it had -- a nonce drawn
    // on a branch that should not have been taken, a field written unconditionally -- this is where
    // it would show, and the compat fixtures would start drifting on every regeneration.
    let a = tmp("det-a");
    let b = tmp("det-b");
    let mut trees = Vec::new();
    for root in [&a, &b] {
        let engine = Engine::init(root, config()).unwrap();
        engine.ingest(events(), 1_760_000_000_000).unwrap();
        trees.push(part_files(&engine));
    }
    assert!(!trees[0].is_empty());
    assert_eq!(
        trees[0].keys().collect::<Vec<_>>(),
        trees[1].keys().collect::<Vec<_>>(),
        "the same input must produce the same parts and files"
    );
    for (name, bytes) in &trees[0] {
        if name.ends_with("manifest.bin") {
            // `created_at_ms` is a wall-clock stamp and was never claimed reproducible.
            continue;
        }
        assert_eq!(
            bytes,
            trees[1].get(name).unwrap(),
            "`{name}` differs between two identical unencrypted ingests"
        );
    }
    for r in [a, b] {
        let _ = std::fs::remove_dir_all(r);
    }
}
