apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prism-shard.fullname" . }}-topology
  labels:
    {{- include "prism-shard.labels" . | nindent 4 }}
data:
  topology.json: |
    {{- .Values.topology | toJson | nindent 4 }}
