apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "prismdb.fullname" . }}
  labels:
    {{- include "prismdb.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prismdb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceLabels | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressPodLabels | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.shardNamespaceLabels | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.shardPodLabels | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.shardPort }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
