apiVersion: v1
kind: Service
metadata:
  name: {{ include "prismdb.fullname" . }}
  labels:
    {{- include "prismdb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "prismdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: mtls-api
      port: {{ .Values.service.port }}
      targetPort: mtls-api
      protocol: TCP
