#!/usr/bin/env bash
# Regenerate the permanent test artifacts (docs/PRISM.md, Part II §7.4).
#
#   testing/compat/  — parts written by every released format version, plus a
#                      corrupt fixture for every way a part can lie to us. These
#                      are committed *bytes*, not a generator: the whole point is
#                      to prove that today's build still opens yesterday's data
#                      and still refuses yesterday's corruption.
#   testing/golden/  — the exact-search corpus and its brute-force ground truth.
#   testing/faults/  — driven by the fault harness; nothing to generate here.
#
# The v1 fixture is NEVER regenerated. It is the bytes S0 shipped, and its whole
# value is that nothing since has touched it. If this script ever rewrites it,
# the compatibility test becomes a tautology.
#
# Run this only when the format version is bumped or the corpus deliberately
# changes. If it produces a diff on an unchanged format, that is a bug, not a
# refresh: something non-deterministic got into the write path.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$(pwd)
PRISM="$ROOT/target/release/prism"
export PYTHONPATH="$ROOT/scripts"

cargo build --release -q

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# ---------------------------------------------------------------- compat, v2
# Small on purpose: a fixture is read by every future version forever, so it
# should be cheap to carry. 200 rows, dim 32, pq_m 4.
echo "==> testing/compat/v2"
rm -rf testing/compat/v2
"$PRISM" gen-corpus --kind uniform --rows 200 --seed 7 --out "$TMP/compat.tsv" >/dev/null
"$PRISM" init --path testing/compat/v2 --dim 32 --nlist 8 --pq-m 4 --seed 7 >/dev/null
"$PRISM" ingest --path testing/compat/v2 --file "$TMP/compat.tsv" >/dev/null
cp "$TMP/compat.tsv" testing/compat/v2-source.tsv
"$PRISM" fsck --path testing/compat/v2 >/dev/null && echo "    v2 fixture is clean"

# ------------------------------------------------------------ compat, corrupt
# Every one of these must be rejected with a *specific* error. A database that
# cannot tell you which byte is wrong will be blamed for corruption it did not
# cause.
#
# They are built by scripts/partfmt.py — an independent Python decoder of the
# binary format, not the Rust writer. A fixture generated by the code under test
# can agree with a bug in it.
echo "==> testing/compat/corrupt-v2"
rm -rf testing/compat/corrupt-v2
mkdir -p testing/compat/corrupt-v2

PART=$(ls testing/compat/v2/parts | head -1)
mk() { rm -rf "testing/compat/corrupt-v2/$1"; cp -R testing/compat/v2 "testing/compat/corrupt-v2/$1"; }

# 1. Not a part at all: the magic is gone.
mk bad-magic
python3 - "$PWD/testing/compat/corrupt-v2/bad-magic/parts/$PART/manifest.bin" <<'PY'
import sys
p = sys.argv[1]
b = bytearray(open(p, "rb").read())
b[0:8] = b"NOTAPART"
open(p, "wb").write(bytes(b))
PY

# 2. The manifest header itself is damaged — caught by its own checksum, before
#    a single field in it is believed.
mk bad-header-crc
python3 - "$PWD/testing/compat/corrupt-v2/bad-header-crc/parts/$PART/manifest.bin" <<'PY'
import sys
p = sys.argv[1]
b = bytearray(open(p, "rb").read())
b[16] ^= 0xFF          # inside the feature flags, before the header crc
open(p, "wb").write(bytes(b))
PY

# 3. A part from the future. Refuse; do not guess.
mk future-format
python3 - "$PWD/testing/compat/corrupt-v2/future-format/parts/$PART/manifest.bin" <<'PY'
import struct, sys, partfmt
p = sys.argv[1]
b = bytearray(open(p, "rb").read())
struct.pack_into("<I", b, 8, 999)                       # format_version
struct.pack_into("<I", b, 32, partfmt.crc32(bytes(b[:32])))   # re-seal the header
open(p, "wb").write(bytes(b))
PY

# 4. A feature bit this build has never heard of. This is the forward-compat
#    escape hatch doing its job: a future version may change what stored bytes
#    mean, and an old reader must refuse rather than misread them.
mk unknown-feature
python3 - "$PWD/testing/compat/corrupt-v2/unknown-feature/parts/$PART/manifest.bin" <<'PY'
import struct, sys, partfmt
p = sys.argv[1]
b = bytearray(open(p, "rb").read())
feats, = struct.unpack_from("<Q", b, 16)
struct.pack_into("<Q", b, 16, feats | (1 << 40))
struct.pack_into("<I", b, 32, partfmt.crc32(bytes(b[:32])))
open(p, "wb").write(bytes(b))
PY

# 5. The manifest body is damaged.
mk bad-body-crc
python3 - "$PWD/testing/compat/corrupt-v2/bad-body-crc/parts/$PART/manifest.bin" <<'PY'
import sys
p = sys.argv[1]
b = bytearray(open(p, "rb").read())
b[40] ^= 0x01          # a byte inside the body; the body crc must catch it
open(p, "wb").write(bytes(b))
PY

# 6. A rerank encoding this build cannot decode (D-003-resolved).
#    Re-sealed, so it is the reader's *dispatch* that refuses it, not a checksum.
#    The day fp16 lands, this fixture is what proves an older binary will not
#    silently read fp16 bytes as float32.
mk unknown-rerank-encoding
python3 - "$PWD/testing/compat/corrupt-v2/unknown-rerank-encoding/parts/$PART/manifest.bin" <<'PY'
import struct, sys, partfmt
p = sys.argv[1]
buf = open(p, "rb").read()
m = partfmt.parse(buf)
def edit(body):
    struct.pack_into("<H", body, m["at"]["rerank_encoding"], 2)   # "fp16", one day
partfmt.patch_body(p, edit)
PY

# 7. A codec id we do not implement.
mk unknown-codec
python3 - "$PWD/testing/compat/corrupt-v2/unknown-codec/parts/$PART/manifest.bin" <<'PY'
import struct, sys, partfmt
p = sys.argv[1]
m = partfmt.parse(open(p, "rb").read())
at = m["columns"][0]["at_codec"]
partfmt.patch_body(p, lambda body: struct.pack_into("<H", body, at, 99))
PY

# 8. A length no bytes could back. The reader must refuse to allocate rather than
#    reserve four billion centroid ranges and take the process with it.
mk absurd-length
python3 - "$PWD/testing/compat/corrupt-v2/absurd-length/parts/$PART/manifest.bin" <<'PY'
import struct, sys, partfmt
p = sys.argv[1]
m = partfmt.parse(open(p, "rb").read())
at = m["at"]["n_ranges"]
partfmt.patch_body(p, lambda body: struct.pack_into("<I", body, at, 0xFFFFFFFF))
PY

# 9. A flipped byte inside one block's payload. It must condemn exactly that
#    block, name it, and leave every other block readable. This is the whole
#    reason block framing exists.
mk block-checksum
python3 - "$PWD/testing/compat/corrupt-v2/block-checksum/parts/$PART" <<'PY'
import os, struct, sys, partfmt
part = sys.argv[1]
m = partfmt.parse(open(os.path.join(part, "manifest.bin"), "rb").read())
col = next(c for c in m["columns"] if c["name"] == "body.data")
f = os.path.join(part, col["file"])
b = bytearray(open(f, "rb").read())
off = col["blocks"][0]["file_offset"] + partfmt.FRAME_HEADER_BYTES + 32
b[off] ^= 0x01                 # payload changes; frame + manifest crcs do not
open(f, "wb").write(bytes(b))
PY

# 10. A truncated column file: the blocks the manifest promised are not there.
mk truncated-column
python3 - "$PWD/testing/compat/corrupt-v2/truncated-column/parts/$PART" <<'PY'
import os, sys, partfmt
part = sys.argv[1]
m = partfmt.parse(open(os.path.join(part, "manifest.bin"), "rb").read())
col = next(c for c in m["columns"] if c["name"] == "rerank_vectors")
f = os.path.join(part, col["file"])
b = open(f, "rb").read()
open(f, "wb").write(b[: len(b) // 2])
PY

# 11. A string offset pointing past the end of its blob. Checksum-valid, and
#     still nonsense: a CRC proves the bytes are the bytes we wrote, not that
#     they mean anything. Every checksum along the way is repaired so that it is
#     the *bounds check* that rejects this and nothing else.
mk bad-offsets
python3 - "$PWD/testing/compat/corrupt-v2/bad-offsets/parts/$PART" <<'PY'
import os, struct, sys, partfmt
part = sys.argv[1]
mpath = os.path.join(part, "manifest.bin")
m = partfmt.parse(open(mpath, "rb").read())
ci = next(i for i, c in enumerate(m["columns"]) if c["name"] == "body.offsets")
col = m["columns"][ci]
f = os.path.join(part, col["file"])

logical = bytearray(partfmt.read_logical(f, col))
struct.pack_into("<q", logical, 8, 1 << 40)      # row 0 ends 1 TiB into the blob
new_crc = partfmt.reframe_block(f, 0, bytes(logical[: col["blocks"][0]["payload_len"]]))

# Fix the manifest's block directory to agree with the frame we just rewrote,
# so the offset validation is the only thing left to catch it.
buf = open(mpath, "rb").read()
m2 = partfmt.parse(buf)
body = bytearray(buf[partfmt.HEADER_BYTES : partfmt.HEADER_BYTES + m2["body_len"]])
# Walk to this column's first block crc: re-parse to find it precisely.
r = partfmt.Reader(bytes(body), m2["at"]["n_columns"])
n = r.u32()
for i in range(n):
    r.string(); r.string(); r.u16(); r.u64()
    nb = r.u32()
    for j in range(nb):
        r.u64(); r.u32()
        at_crc = r.pos
        r.u32()
        if i == ci and j == 0:
            struct.pack_into("<I", body, at_crc, new_crc)
open(mpath, "wb").write(partfmt.reseal(buf, body))
PY

# 12. A codebook edited in place: the generation no longer hashes to its own id,
#     which means every code byte in every part just changed meaning.
mk mutated-codebook
python3 - "$PWD/testing/compat/corrupt-v2/mutated-codebook" <<'PY'
import json, os, sys
root = sys.argv[1]
gens = os.path.join(root, "generations")
f = os.path.join(gens, os.listdir(gens)[0])
g = json.load(open(f))
g["coarse"]["centroids"][0] += 0.5
json.dump(g, open(f, "w"), indent=2)
PY

echo "    built $(ls testing/compat/corrupt-v2 | wc -l | tr -d ' ') corrupt v2 fixtures"

# ---------------------------------------------------------------- golden corpus
echo "==> testing/golden"
mkdir -p testing/golden
"$PRISM" gen-corpus --kind zipf --rows 2000 --seed 1234 --out testing/golden/corpus.tsv >/dev/null
rm -rf "$TMP/golden"
"$PRISM" init --path "$TMP/golden" --dim 64 --nlist 32 --pq-m 8 --seed 1234 >/dev/null
"$PRISM" ingest --path "$TMP/golden" --file testing/golden/corpus.tsv >/dev/null
"$PRISM" golden build --path "$TMP/golden" --out testing/golden/expected.json --k 10 --kind zipf

# The nprobe default is not a round number someone liked. It is the smallest
# probe count that holds p1 recall@10 at or above the floor on this corpus, and
# this file is the receipt.
"$PRISM" golden sweep --path "$TMP/golden" --golden testing/golden/expected.json \
  --out testing/golden/nprobe-provenance.json --p1-floor 0.8

echo
echo "Fixtures regenerated. Review the diff: on an unchanged format there should be none."
