"""An independent decoder for the PrismDB v2 part format.

Deliberately *not* the Rust code. This is a second implementation, written from
the format definition, used to build the corrupt fixtures the reader must reject.
Two things fall out of that:

  * The fixtures are not generated by the code under test, so they cannot
    accidentally agree with a bug in it.
  * If someone changes the format and forgets to think about compatibility, this
    file stops parsing and the fixture script fails loudly — which is exactly the
    conversation we want to force.

Layout (all little-endian):

  header  magic[8] "PRSMPART" | version u32 | byte_order u8 | reserved[3]
          | features u64 | body_len u32 | body_crc32 u32 | header_crc32 u32
  body    part_id str | generation_id str | model_id str | model_version str
          | row_count u64 | dim u32 | pq_m u32
          | rerank_encoding u16 | rerank_contract u16
          | time_min i64 | time_max i64 | cost_min f64 | cost_max f64
          | flags u8 | created_at_ms i64
          | n_tenants u32 [str...]
          | n_ranges u32 [centroid u32, first_row u64, row_count u64,
                          pq_offset u64, pq_len u64, rerank_offset u64,
                          rerank_len u64, time_min i64, time_max i64]
          | n_columns u32 [name str, file str, codec u16, logical_bytes u64,
                           n_blocks u32 [file_offset u64, payload_len u32, crc32 u32]]

  column file  per block: magic u32 "PBLK" | index u32 | logical_offset u64
               | payload_len u32 | crc32 u32 | payload[payload_len]
"""

import struct
import zlib

MAGIC = b"PRSMPART"
HEADER_BYTES = 36
BLOCK_MAGIC = 0x4B4C4250
FRAME_HEADER_BYTES = 24
BLOCK_SIZE = 64 * 1024


def crc32(b: bytes) -> int:
    return zlib.crc32(b) & 0xFFFFFFFF


class Reader:
    def __init__(self, buf, pos=0):
        self.buf = buf
        self.pos = pos

    def take(self, n):
        v = self.buf[self.pos : self.pos + n]
        assert len(v) == n, f"truncated at {self.pos}"
        self.pos += n
        return v

    def u8(self):
        return self.take(1)[0]

    def u16(self):
        return struct.unpack("<H", self.take(2))[0]

    def u32(self):
        return struct.unpack("<I", self.take(4))[0]

    def u64(self):
        return struct.unpack("<Q", self.take(8))[0]

    def i64(self):
        return struct.unpack("<q", self.take(8))[0]

    def f64(self):
        return struct.unpack("<d", self.take(8))[0]

    def string(self):
        n = self.u32()
        return self.take(n).decode()


def parse_header(buf):
    assert buf[:8] == MAGIC, "not a part manifest"
    version, byte_order = struct.unpack_from("<IB", buf, 8)
    features, body_len, body_crc, header_crc = struct.unpack_from("<QIII", buf, 16)
    return {
        "version": version,
        "byte_order": byte_order,
        "features": features,
        "body_len": body_len,
        "body_crc": body_crc,
        "header_crc": header_crc,
    }


def parse(buf):
    """Parse a manifest; returns field values plus the byte offset of each field
    we may want to corrupt."""
    h = parse_header(buf)
    body = buf[HEADER_BYTES : HEADER_BYTES + h["body_len"]]
    r = Reader(body)

    out = {"header": h, "body_len": h["body_len"], "at": {}}
    out["part_id"] = r.string()
    out["generation_id"] = r.string()
    out["model_id"] = r.string()
    out["model_version"] = r.string()
    out["row_count"] = r.u64()
    out["dim"] = r.u32()
    out["pq_m"] = r.u32()

    out["at"]["rerank_encoding"] = r.pos  # <- body-relative
    out["rerank_encoding"] = r.u16()
    out["at"]["rerank_contract"] = r.pos
    out["rerank_contract"] = r.u16()

    r.i64(), r.i64(), r.f64(), r.f64(), r.u8(), r.i64()

    n_tenants = r.u32()
    out["tenants"] = [r.string() for _ in range(n_tenants)]

    out["at"]["n_ranges"] = r.pos
    n_ranges = r.u32()
    out["n_ranges"] = n_ranges
    ranges = []
    for _ in range(n_ranges):
        ranges.append(
            {
                "centroid": r.u32(),
                "first_row": r.u64(),
                "row_count": r.u64(),
                "pq_offset": r.u64(),
                "pq_len": r.u64(),
                "rerank_offset": r.u64(),
                "rerank_len": r.u64(),
                "time_min": r.i64(),
                "time_max": r.i64(),
            }
        )
    out["ranges"] = ranges

    out["at"]["n_columns"] = r.pos
    n_cols = r.u32()
    cols = []
    for _ in range(n_cols):
        name = r.string()
        file = r.string()
        at_codec = r.pos
        codec = r.u16()
        logical = r.u64()
        # v3: per-column block size. v2 had none (every column was 64 KiB).
        block_size = r.u32() if h["version"] >= 3 else 65536
        n_blocks = r.u32()
        blocks = []
        for _ in range(n_blocks):
            blocks.append(
                {"file_offset": r.u64(), "payload_len": r.u32(), "crc32": r.u32()}
            )
        cols.append(
            {
                "name": name,
                "file": file,
                "codec": codec,
                "at_codec": at_codec,
                "logical_bytes": logical,
                "block_size": block_size,
                "blocks": blocks,
            }
        )
    out["columns"] = cols

    # --- v3 additions ---
    if h["version"] >= 3:
        out["at"]["n_attribute_keys"] = r.pos
        n_keys = r.u32()
        out["attribute_keys"] = [r.string() for _ in range(n_keys)]
        out["at"]["reserved"] = r.pos
        out["reserved"] = [r.u64() for _ in range(4)]
        out["at"]["n_extensions"] = r.pos
        n_ext = r.u32()
        exts = []
        for _ in range(n_ext):
            eid = r.u16()
            elen = r.u32()
            exts.append({"id": eid, "bytes": r.take(elen)})
        out["extensions"] = exts

    assert r.pos == len(body), f"trailing bytes in body: {r.pos} != {len(body)}"
    return out


def reseal(buf, body):
    """Rebuild a manifest around a (possibly edited) body, fixing both checksums.

    Used when a fixture needs the *semantic* check to be what rejects it, rather
    than the checksum -- e.g. an unknown rerank encoding must be refused because
    the reader dispatches on it, not because the CRC caught us editing it.
    """
    out = bytearray(buf[:HEADER_BYTES])
    struct.pack_into("<I", out, 24, len(body))
    struct.pack_into("<I", out, 28, crc32(body))
    struct.pack_into("<I", out, 32, crc32(bytes(out[:32])))
    return bytes(out) + bytes(body)


def patch_body(path, edit):
    """Read a manifest, hand its mutable body to `edit`, reseal, write back."""
    buf = open(path, "rb").read()
    h = parse_header(buf)
    body = bytearray(buf[HEADER_BYTES : HEADER_BYTES + h["body_len"]])
    edit(body)
    open(path, "wb").write(reseal(buf, body))


def reframe_block(col_path, block_index, new_payload):
    """Rewrite one block's payload and its frame checksum in a column file.

    Returns the new crc, so the caller can also fix the manifest's block
    directory -- otherwise the manifest and the frame disagree, which is itself a
    (different) thing the reader must catch.
    """
    buf = bytearray(open(col_path, "rb").read())
    pos = 0
    for i in range(block_index + 1):
        magic, idx, logical_off, payload_len, crc = struct.unpack_from("<IIQII", buf, pos)
        assert magic == BLOCK_MAGIC, f"bad block magic at {pos}"
        if i == block_index:
            assert len(new_payload) == payload_len, "payload length must not change"
            new_crc = crc32(new_payload)
            struct.pack_into("<I", buf, pos + 20, new_crc)
            buf[pos + FRAME_HEADER_BYTES : pos + FRAME_HEADER_BYTES + payload_len] = new_payload
            open(col_path, "wb").write(bytes(buf))
            return new_crc
        pos += FRAME_HEADER_BYTES + payload_len
    raise AssertionError("block not found")


def read_logical(col_path, manifest_col):
    """Reassemble a column's logical byte stream from its blocks."""
    buf = open(col_path, "rb").read()
    out = bytearray()
    for i, b in enumerate(manifest_col["blocks"]):
        pos = b["file_offset"]
        magic, idx, logical_off, payload_len, crc = struct.unpack_from("<IIQII", buf, pos)
        assert magic == BLOCK_MAGIC and idx == i
        out += buf[pos + FRAME_HEADER_BYTES : pos + FRAME_HEADER_BYTES + payload_len]
    return bytes(out)
